### ISSUE TITLE
Add a tempo box to allow the user to input the tempo

### ISSUE THREAD

**Issue by RMRattray** [Purdue-Artificial-Intelligence-in-Music/Companion-code#156]
There is, as yet, no way for the user to specify the desired play tempo.  Also, the cursor moves based on the tempo of the score (off the musicXML file) - this needs to be extracted for the cursor to work correctly.

**Comment by rtjord** [comment]
Use the tempo provided by the user to calculate the number of whole notes in the score and then move the cursor to that position
