### ISSUE TITLE
Remove PyTest workflow

### ISSUE THREAD

**Issue by rtjord** [Purdue-Artificial-Intelligence-in-Music/Companion-code#76]

**Comment by NickKo0517** [comment]
Hey Ryan, I am not too sure about what to do with this issue. I did not remember setting up a workflow named PyTest. Am I suppose to fix the dependencies installation issue we see in the "Auto Test Python Code" action (which is configured in auto_test.yml) here? (BTW, I may want to switch the testing framework from unittest to pytest as most tutorials I found online make uses of pytest)
