### ISSUE TITLE
Improve cursor control for frontend

### ISSUE THREAD

**Issue by rtjord** [Purdue-Artificial-Intelligence-in-Music/Companion-code#93]

**Comment by RMRattray** [comment]
In my notes, I wrote to implement automatic scrolling and to see if the cursor can be moved to a certain note - for the latter, what would be given about that note - its timestamp?  A reference to the Note object?

**Comment by RMRattray** [comment]
Don't close the issue when the pull request is merged!  I'm still "improving the cursor control," after all.
